#!/usr/bin/env node
/**
 * build.js — Claims Resilience Tool bundler
 *
 * Produces dist/index.html: a single self-contained file that works when
 * opened directly via file:// (no HTTP server needed).
 *
 * What it does:
 *   1. Reads index.html
 *   2. Reads every JSON config file and inlines each as a named const
 *      (CONFIG_DEFAULTS, CONFIG_CLAIM_PATTERNS, …) directly inside the
 *      main <script> block (const is block-scoped to its <script> tag).
 *   3. The runtime loadAllConfig() function already detects these constants
 *      and skips fetch() — so the same source works in both dev and bundled modes.
 *   4. Writes the result to dist/index.html.
 *
 * Note on ES modules: the application currently uses a single inline <script>
 * with no import/export statements, so no module resolution is required.
 * If src/ modules are added in future, extend the "Inline JS modules" section below.
 *
 * Usage:
 *   node build.js
 */

'use strict';

const fs   = require('fs');
const path = require('path');

const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');

// ── Config file → injected variable name ────────────────────────────────────
// Order matches the fetch order in loadAllConfig() — keep in sync.
const CONFIG_FILES = [
  { file: 'config/defaults.json',              varName: 'CONFIG_DEFAULTS'             },
  { file: 'config/claim-categories.json',      varName: 'CONFIG_CLAIM_CATEGORIES'     },
  { file: 'config/legal-framework.json',       varName: 'CONFIG_LEGAL_FRAMEWORK'      },
  { file: 'config/historical-data.json',       varName: 'CONFIG_HISTORICAL_DATA'      },
  { file: 'config/distribution-templates.json',varName: 'CONFIG_DISTRIBUTION_TEMPLATES'},
  { file: 'config/time-horizons.json',         varName: 'CONFIG_TIME_HORIZONS'        },
  { file: 'config/claim-patterns.json',        varName: 'CONFIG_CLAIM_PATTERNS'       },
  { file: 'config/claim-values.json',          varName: 'CONFIG_CLAIM_VALUES'         },
  { file: 'config/mc-defaults.json',           varName: 'CONFIG_MC_DEFAULTS'          },
  { file: 'config/historical-validation.json', varName: 'CONFIG_HISTORICAL_VALIDATION'},
];

// ── 1. Read source HTML ──────────────────────────────────────────────────────
const srcPath = path.join(ROOT, 'index.html');
if (!fs.existsSync(srcPath)) {
  console.error('ERROR: index.html not found at', srcPath);
  process.exit(1);
}
let html = fs.readFileSync(srcPath, 'utf8');

// ── 2. Build inline config declarations ─────────────────────────────────────
const configDeclarations = CONFIG_FILES.map(({ file, varName }) => {
  const filePath = path.join(ROOT, file);
  if (!fs.existsSync(filePath)) {
    console.error(`ERROR: config file not found: ${file}`);
    process.exit(1);
  }
  let data;
  try {
    data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (e) {
    console.error(`ERROR: failed to parse ${file}:`, e.message);
    process.exit(1);
  }
  return `const ${varName} = ${JSON.stringify(data, null, 2)};`;
});

const inlineConfigJS =
  `// ── Inlined config — generated by build.js, do not edit this block ────────\n` +
  configDeclarations.join('\n\n') + '\n' +
  `// ── End inlined config ────────────────────────────────────────────────────\n`;

// ── 3. Inline JS modules (future use) ───────────────────────────────────────
// The application currently uses a single inline <script> with no ES module
// imports. When src/ modules are introduced, resolve and concatenate them here
// before injecting. Nothing to do for now.

// ── 4. Inject config inside the main <script> block ─────────────────────────
// The config constants must live in the SAME <script> tag as the application
// code, because const/let declarations are scoped to their <script> element
// and are not visible from a different <script> tag.
const SCRIPT_TAG = '<script>';
const markerIndex = html.indexOf(SCRIPT_TAG);
if (markerIndex === -1) {
  console.error('ERROR: could not find <script> tag in index.html');
  process.exit(1);
}
// Insert right after "<script>\n"
const insertPos = markerIndex + SCRIPT_TAG.length;
html = html.slice(0, insertPos) + '\n' + inlineConfigJS + html.slice(insertPos);

// ── 5. Write dist/index.html ─────────────────────────────────────────────────
if (!fs.existsSync(DIST)) {
  fs.mkdirSync(DIST, { recursive: true });
}
const outPath = path.join(DIST, 'index.html');
fs.writeFileSync(outPath, html, 'utf8');

const sizeKB = (Buffer.byteLength(html, 'utf8') / 1024).toFixed(1);
console.log(`Built dist/index.html  (${sizeKB} KB)`);
console.log(`Inlined ${CONFIG_FILES.length} config files:`);
CONFIG_FILES.forEach(({ file, varName }) => console.log(`  ${varName}  ←  ${file}`));
